MiniProject.Web/Controllers/MCompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MiniProject.Model;
using MiniProject.VM;
using MiniProject.Repo;

namespace MiniProject.Web.Controllers
{
    
    public class MCompanyController : Controller
    {
        // GET: m_company
        public ActionResult Index()
        {
            ViewBag.Title = "List Company";
            ViewBag.ListCompanyCode = new SelectList(MCompanyRepo.get(), "code", "code");
            ViewBag.ListCompanyName = new SelectList(MCompanyRepo.get(), "name", "name");
            List<MCompanyVM> item = MCompanyRepo.get();
            return View(item);
        }

        public ActionResult List()
        {
            List<MCompanyVM> item = MCompanyRepo.get();
            return PartialView("_List", item);
        }

        public ActionResult Add()
        {
            MCompanyVM model = new MCompanyVM();
            model.code = MCompanyRepo.KodeAuto();
            ViewBag.Title = "Add";
            return PartialView("_Add",model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(MCompanyVM model)
        {
            if(ModelState.IsValid)
            {
                if (MCompanyRepo.CheckCompany(model) == true)
                {
                    var result = new
                    {
                        success = true,
                        alertType = "warning",
                        alertStrong = "Error !",
                        alertMessage = "Company Already Created"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else if (MCompanyRepo.CheckCompany(model) == false)
                {
                    MCompanyRepo.insert(model);
                    var result = new
                    {
                        success = false,
                        alertType = "success",
                        alertStrong = "Data Saved !",
                        alertMessage = "New company has been add with Code" + model.code
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            return PartialView("_Add",model);
        }

        public ActionResult Detail(int id)
        {
            MCompanyVM model = MCompanyRepo.GetDetail(id);
            ViewBag.Title = "View Company-" +model.name + "(" + model.code + ")";
               
                
            return PartialView(model);
        }

        public ActionResult Edit (int id)
        {

            MCompanyVM model = MCompanyRepo.getbyid(id);
            
            return PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MCompanyVM model)
        {
            if (ModelState.IsValid)
            {
                if (MCompanyRepo.CheckCompany(model) == true)
                {
                    var result = new
                    {
                        success = true,
                        alertType = "warning",
                        alertStrong = "Error !",
                        alertMessage = "Company Already Created"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else if (MCompanyRepo.CheckCompany(model) == false)
                {
                    MCompanyRepo.update(model);
                    var result = new
                    {
                        success = false,
                        alertType = "success",
                        alertStrong = "Data Updated !",
                        alertMessage = "Data company has been Updated"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            return PartialView(model);
        }

        public ActionResult Delete(int id)
        {
            MCompanyVM model = MCompanyRepo.getbyid(id);
            if (MEmployeeRepo.Hitung(model.id) == true)
            {
                var result = new
                {
                    success = true,
                    alertType = "warning",
                    alertStrong = "Error!",
                    alertMessage = "Company still has employees"
                };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else if (MEmployeeRepo.Hitung(model.id) == false)
            {
                MCompanyRepo.Delete(model);
                var result = new
                {
                    success = false,
                    alertType = "success",
                    alertStrong = "Data Deleted !",
                    alertMessage = "Data Deleted! Data Company With Code" + model.code + "Has been delete"
                };
                return Json(result, JsonRequestBehavior.AllowGet);

            }
            return PartialView("_Delete", model);
        }

        public JsonResult CheckNama(string nama)
        {
            var result = new
            {
                success = true,
                data = MCompanyRepo.CheckNameCompany(nama),
                alertType = "error",
                alertStrong = "Error !",
                alertMessage = "Your Data with name </strong>(" + nama + ")</strong>Has been created"
            };
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        
        //[HttpPost]
        //public ActionResult Delete(m_companyVM model)
        //{
           

        //    return PartialView("_Delete",model);
        //}

        //public ActionResult SearchData(m_companyVM model)
        //{
        //    var data = m_companyRepo.SearchData(model);
        //    if (data.Count == 0 && model.code == null && model.name == null && model.created_date == DateTime.MinValue && model.created_by == 0)
        //    {
        //        data = m_companyRepo.get();
        //    }

        //    return PartialView("_List", data);
        //}
    }
}

MiniProject.Web/Controllers/MMenuController.cs
using MiniProject.Repo;
using MiniProject.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiniProject.Web.Controllers
{
    public class MMenuController : Controller
    {
        // GET: Menu_
        public ActionResult Index()
        {
            ViewBag.ListCode = new SelectList(MMenuRepo.get(), "code", "code");
            ViewBag.ListName = new SelectList(MMenuRepo.get(), "name", "name");
            List<MMenuVM> data = MMenuRepo.get();
            return View(data);
        }

        public ActionResult List()
        {
            List<MMenuVM> data = MMenuRepo.get();
            return PartialView("_List", data);
        }

        public ActionResult Add()
        {
            MMenuVM model = new MMenuVM();
            model.code = MMenuRepo.NewCode();
            ViewBag.ListParent = new SelectList(MMenuRepo.get(), "name", "name");
            return PartialView("_Add", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(MMenuVM model)
        {
            if (ModelState.IsValid)
            {
                if (MMenuRepo.CekNama(model)==true)
                {
                    var result = new
                    {
                        success = false,
                        alertType = "error",
                        alertStrong = "Error!",
                        alertMessage = "Menu name already used"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else if (MMenuRepo.CekNama(model)==false)
                {
                    MMenuRepo.insert(model);
                    var result = new
                    {
                        success = true,
                        alertType = "info",
                        alertStrong = "Data Saved !",
                        alertMessage = "New menu has been added with code " + model.code + " !"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            return PartialView(model);
        }

        public JsonResult CekNama(string nama)
        {
            var result = new
            {
                success = true,
                data = MMenuRepo.CekNama(nama),
                alertType = "warning",
                alertStrong = "Error !",
                alertMessage = "Menu name with name </strong>" + nama + "</strong> already used"
            };
            return Json(result, JsonRequestBehavior.AllowGet);
        }
 
        public ActionResult Edit(int id)
        {
            ViewBag.ListParent = new SelectList(MMenuRepo.get(), "name", "name");
            return PartialView("_Edit", MMenuRepo.getById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MMenuVM model)
        {
            if (ModelState.IsValid)
            {
                if (MMenuRepo.CekNama2(model) == true)
                {
                    var result = new
                    {
                        success = false,
                        alertType = "error",
                        alertStrong = "Error!",
                        alertMessage = "Menu name already used"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else if (MMenuRepo.CekNama2(model) == false)
                {
                    MMenuRepo.Edit(model);
                    var result = new
                    {
                        success = true,
                        alertType = "info",
                        alertStrong = "Data Updated !",
                        alertMessage = "Data menu has been updated !"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }

            }
            return PartialView("_Edit", model);
        }

        public ActionResult HideMenu(int id)
        {
            if (MMenuRepo.hiddenMenu(id) == true)
            {
                var result = new
                {
                    success = true,
                    message = "Data Berhasil Di Delete"
                };
                return Json(result, JsonRequestBehavior.AllowGet);
            }

            return RedirectToAction("index");
        }

        public ActionResult Detail(int id)
        {
            MMenuVM menu = MMenuRepo.getById(id);
            return PartialView("_Detail", menu);
        }

    }
}

MiniProject.Web/Controllers/MRoleController.cs
using MiniProject.Repo;
using MiniProject.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiniProject.Web.Controllers
{
    public class MRoleController : Controller
    {
        // GET: Role_
        public ActionResult Index()
        {
            ViewBag.ListCode = new SelectList(MRoleRepo.get(),"code","code");
            ViewBag.ListName = new SelectList(MRoleRepo.get(), "name", "name");
            List<MRoleVM> data = MRoleRepo.get();
            return View(data);
        }

        public ActionResult List()
        {
            List<MRoleVM> data = MRoleRepo.get();
            return PartialView("_List", data);
        }

        public ActionResult Add()
        {
            MRoleVM model = new MRoleVM();
            model.code = MRoleRepo.NewCode();
            return PartialView("_Add", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(MRoleVM model)
        {
            if (ModelState.IsValid)
            {
                if (MRoleRepo.CekNama(model) == true)
                {
                    var result = new
                    {
                        success = false,
                        alertType = "error",
                        alertStrong = "Error!",
                        alertMessage = "Role name already used"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else if (MRoleRepo.CekNama(model) == false)
                {
                    MRoleRepo.insert(model);
                    var result = new
                    {
                        success = true,
                        alertType = "info",
                        alertStrong = "Data Saved !",
                        alertMessage = "New role has been added with code " + model.code + " !"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }
            return PartialView("_Add", model);
        }

        public JsonResult CekNama(string nama)
        {
            var result = new
            {
                success = true,
                data = MRoleRepo.CekNama(nama),
                alertType = "warning",
                alertStrong = "Error !",
                alertMessage = "Role name with name </strong>" + nama + "</strong> already used"
            };
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit(int id)
        {
            return PartialView("_Edit", MRoleRepo.getById(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MRoleVM model)
        {
            if (ModelState.IsValid)
            {
                if (MRoleRepo.CekNama2(model) == true)
                {
                    var result = new
                    {
                        success = false,
                        alertType = "error",
                        alertStrong = "Error!",
                        alertMessage = "Role name already used"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else if (MRoleRepo.CekNama2(model) == false)
                {
                    MRoleRepo.Edit(model);
                    var result = new
                    {
                        success = true,
                        alertType = "info",
                        alertStrong = "Data Updated !",
                        alertMessage = "Data Role has been updated !"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }
            return PartialView("_Edit", model);
        }

        public ActionResult HideRole(int id)
        {
            if (MRoleRepo.hiddenRole(id) == true)
            {
                var result = new
                {
                    success = true,
                    message = "Data Berhasil Di Delete"
                };
                return Json(result, JsonRequestBehavior.AllowGet);
            }

            return RedirectToAction("index");
        }

        public ActionResult Detail(int id)
        {
            MRoleVM role = MRoleRepo.getById(id);
            return PartialView("_Detail", role);
        }
    }
}

MiniProject.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue-light sidebar-mini">
    <div class="wrapper">
        @Html.Partial("_Header")
        @Html.Partial("_Sidebar")

        <div class="content-wrapper">
            <section class="content-header">
                <h1>
                    @ViewBag.ContentHeader
                    <small>@ViewBag.Title</small>
                </h1>

                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-dashboard"></i> @ViewBag.Route</a></li>
                    <li class="active">@ViewBag.Action</li>
                </ol>
            </section>
            <section class="content">
                <div class="row">
                    <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
                        @RenderBody()
                    </div>
                </div>
            </section>
        </div>

        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                All rights reserved.
            </div>
            <strong>Copyright &copy; @DateTime.Now.Year <a href="#"<i class="fa fa-heart" style="color:deeppink;"></i></a> BATCH 164.</strong>
        </footer>

    </div>

    @Scripts.Render("~/bundles/jquery")

    @section Scripts {
        <script>
            $.widget.bridge('uibutton', $.ui.button);
        </script>
    }

    @Scripts.Render("~/bundles/bootstrap")
    <script>
        $(function () {
            $('[data-mask]').inputmask();
            $('.select2').select2();
        })

        $(document).ready(function () {
            $(".box-body").find(".col-md-2").css("padding-right", "unset");
            $('.datatable').DataTable({
                'sDom': 'tip',
                autoWidth: true
            });
            $('#created_date').datepicker({
                format: 'dd-mm-yyyy',
                autoclose: true
            });
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

MiniProject.Web/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
    <div class="wrapper">
        @*@Html.Partial("_Header")
            @Html.Partial("_Sidebar")*@
        <section class="content">
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
                    @RenderBody()

                </div>
            </div>

        </section>
    </div>

    @Scripts.Render("~/bundles/jquery")

    @section Scripts {
        <script>
            $.widget.bridge('uibutton', $.ui.button);
        </script>
    }

    @Scripts.Render("~/bundles/bootstrap")
    <script>
        $(function () {
            $('[data-mask]').inputmask();
            $('.select2').select2();

            $('.icheck').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' /* optional */
            });
        })
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

MiniProject.Web/Views/Shared/_Sidebar.cshtml
<aside class="main-sidebar ">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="~/img/user2-160x160.jpg" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>@User.Identity.Name</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            <li>
                <a href="@Url.Action("Index","MCompany")">
                    <i class="fa fa-home"></i> <span>Company</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index","MEmployee")">
                    <i class="fa fa-shopping-bag"></i> <span>Employee</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index","MRole")">
                    <i class="fa fa-shopping-bag"></i> <span>Role</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index","MMenu")">
                    <i class="fa fa-home"></i> <span>Menu</span>
                </a>
            </li>
            <li>
<li>
                <a href="@Url.Action("Index","MUnit")">
                    <i class="fa fa-home"></i> <span>Unit</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index","MSouvenir")">
                    <i class="fa fa-home"></i> <span>Souvenir</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index","MProduct")">
                    <i class="fa fa-shopping-bag"></i> <span>Product</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index","MMenuAccess")">
                    <i class="fa fa-shopping-cart"></i> <span>Menu Access</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index","user")">
                    <i class="fa fa-shopping-basket"></i> <span>User</span>
                </a>
            </li>


        </ul>
    </section>
    <!-- /.sidebar -->
</aside>