MiniProject.Web/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MiniProject.Model;
using MiniProject.VM;
using MiniProject.Repo;

namespace MiniProject.Web.Controllers
{
    public class AjaxController : Controller
    {
        // GET: Ajax
        public ActionResult GetById(int id)
        {
            var data = new
            {
                obj = MCompanyRepo.getbyid(id)
            };
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetById2(int id)
        {
            var data = new
            {
                obj = MEmployeeRepo.getbyid(id)
            };
            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

MiniProject.Web/Controllers/MSouvenirController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MiniProject.ViewModel;
using MiniProject.Repo;

namespace MiniProject.Web.Controllers
{
    [Authorize]
    public class MSouvenirController : Controller
    {
        public ActionResult Masking()
        {
            return View();
        }

        // GET: MSouvenir
        public ActionResult Index()
        {
            var data = MSouvenirRepo.GetAllData();

            ViewBag.listUnit = new SelectList(mUnitRepo.get(), "name", "name");
            return View(data);
        }

        public ActionResult List()
        {
            var data = MSouvenirRepo.GetAllData();
            return PartialView("_List", data);
        }

        public ActionResult Detail(int id)
        {
            var jsonParse = new
            {
                data = MSouvenirRepo.GetId(id)
            };
            Json(jsonParse, JsonRequestBehavior.AllowGet);

            ViewBag.listUnit = new SelectList(mUnitRepo.get(), "id", "name");
            return PartialView("_Detail", jsonParse.data);
        }

        public ActionResult SearchData(MSouvenirVM model)
        {
            var data = MSouvenirRepo.SearchData(model);
            if (data.Count == 0 && model.code == null && model.name == null && model.m_unit_id == 0 && model.created_date == DateTime.MinValue && model.created_by == 0)
            {
                data = MSouvenirRepo.GetAllData();
            }

            return PartialView("_List", data);
        }

        public ActionResult Insert()
        {
            ViewBag.AutoCode = MSouvenirRepo.AutoCode();
            ViewBag.listUnit = new SelectList(mUnitRepo.get(), "id", "name");
            return PartialView("_Insert");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Insert(MSouvenirVM model)
        {
            if (ModelState.IsValid)
            {
                if (MSouvenirRepo.CheckIfExists(model) == true)
                {
                    var notif = new
                    {
                        success = false,
                        alertType = "error",
                        alertMessage = "ERROR !",
                        alertStrong = "Your Data With Name (" + model.name + ") is Already Exists"
                    };
                    return Json(notif, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    MSouvenirRepo.Insert(model);
                    var result = new
                    {
                        success = true,
                        alertType = "info",
                        alertMessage = "Saved !",
                        alertStrong = "Your Data With Code <strong>(" + model.code + ")</strong> is Saved"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }
            return PartialView("_Insert");
        }

        public ActionResult Update(int id)
        {
            ViewBag.listUnit = new SelectList(mUnitRepo.get(), "id", "name");
            return PartialView("_Update", MSouvenirRepo.GetId(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(MSouvenirVM model)
        {
            if (ModelState.IsValid)
            {
                if (MSouvenirRepo.CheckIfExists(model) == true)
                {
                    var notif = new
                    {
                        success = false,
                        alertType = "error",
                        alertMessage = "ERROR !",
                        alertStrong = "Your Data With Name <strong>(" + model.name + ")</strong> is Already Exists"
                    };
                    return Json(notif, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    MSouvenirRepo.Update(model);
                    var result = new
                    {
                        success = true,
                        alertType = "info",
                        alertMessage = "Updated !",
                        alertStrong = "Your Data With Code <strong>(" + model.code + ")</strong> is Updated"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }
            return PartialView("_Update");
        }

        public ActionResult Delete(int id)
        {
            var data = MSouvenirRepo.GetId(id);
            MSouvenirRepo.Delete(id);
            var result = new
            {
                success = true,
                item = data,
                alertType = "info",
                alertStrong = "Deleted !",
                alertMessage = "Your Data With Code <strong>(" + data.code + ")</strong> is Deleted"
            };
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

MiniProject.Web/Views/MSouvenir/Index.cshtml
@model IEnumerable<MiniProject.ViewModel.MSouvenirVM>

@{
    ViewBag.Title = "Master";
    ViewBag.ContentHeader = "List Souvenir";
    ViewBag.Route = "Souvenir";
    ViewBag.Action = "List Souvenir";
}

<div id="AlertResponse"></div>

<div class="box box-primary box-solid">
    <div class="box-header">
        <h3 class="box-title"></h3>
        <div class="box-tools">

        </div>
    </div>
    <div class="box-body">
        <p>
            <div class="row">
                <div class="col-md-12">
                    <button class="btn btn-primary btn-sm" id="btn-add" style="width:5em;">Add</button>
                </div>
            </div>
        </p>
        <table></table>

        @using (Html.BeginForm("SearchData", "MSouvenir", FormMethod.Post, new { @id = "form-search" }))
        {
            <table class="table table-bordered table-striped table-responsive datatable">

                <thead>
                    <tr id="col-input">
                        <td>
                            <input type="text" name="code" id="code" value="" datacolumn="0" class="col0 form-control" placeholder="Souvenir Code" />
                        </td>
                        <td>
                            <input type="text" name="name" id="name" value="" datacolumn="1" class="col1 form-control" placeholder="Souvenir Name" />
                        <td>
                            @Html.DropDownList("m_unit_id", (IEnumerable<SelectListItem>)ViewBag.listUnit, "--Select Unit Item--", new { @class = "form-control select2 col2", @datacolumn = "2" })
                        </td>
                        <td>
                            <div class="input-group date">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <input type="text" class="col3 form-control" id="created_date" datacolumn="3" name="created_date" data-provide="datepicker" placeholder="Created">
                            </div>
                        </td>
                        <td>
                            <input type="text" name="created_by" id="created_by" value="" datacolumn="4" class="col4 form-control" placeholder="Created By" />
                        </td>
                        <td>
                            <button type="button" class="btn btn-warning btn-sm pull-right" id="btn-search" style="width:5em;">Search</button>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(m => m.code)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.str_unit)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.created_date)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.str_created_by)
                        </th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody id="list-data">
                    @Html.Partial("_List", Model)
                </tbody>
            </table>
        }
    </div>
</div>

<div class="modal fade" id="getModal">
    <div class="modal-dialog modal-lg" role="dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title"></h3>

            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        


        //----------------------------------------------------------------

        $('#btn-search').click(function () {
            var data = $("#col-input .form-control").each(function (i) {
                filterColumn($(this).attr('datacolumn'));
            });
        });

        function filterColumn(i) {
            var data = $(".col" + i).val();
            $('.datatable').DataTable().column(i).search(data).draw();
        }

        function LoadData() {
            $.ajax({
                url: '@Url.Action("List")',
                type: 'get',
                dataType: 'html',
                success: function (x) {
                    $("#list-data").html(x);
                }
            });
        }

        function clickbyID(action, id) {
            $.ajax({
                url: '@Url.Action("GetById","Ajax")',
                type: 'get',
                dataType: 'json',
                data: {
                    id: id
                },
                success: function (y) {
                    var vCode = y.obj.code;
                    var vName = y.obj.name;

                    $.ajax({
                        url: '/MSouvenir/' + action + "/" + id,
                        type: 'get',
                        dataType: 'html',
                        success: function (x) {
                            $("#getModal").modal('show');
                            $("#getModal").find(".modal-title").html(action + " Souvenir " + vName + " (" + vCode + ")");
                            $("#getModal").find(".modal-body").html(x);
                        }
                    });
                }
            });
        }

        function Delete(id) {
            $.ajax({
                url: '@Url.Action("GetById","Ajax")',
                type: 'get',
                dataType: 'json',
                data: {
                    id: id
                },
                success: function (x) {
                    Swal({
                        title: 'Delete ' + x.obj.name + ' (' + x.obj.code + ')?',
                        text: 'Are you sure?',
                        type: 'warning',
                        showCancelButton: true,
                        confirmButtonText: 'Yes, delete it!',
                        cancelButtonText: 'cancel!',
                        reverseButtons: true
                    }).then((result) => {
                        if (result.value) {
                            $.ajax({
                                url: '/MSouvenir/Delete/' + id,
                                type: 'get',
                                dataType: 'json',
                                success: function (x) {
                                    if (x.success == true) {
                                        swal(
                                            'Deleted!',
                                            'Your file has been deleted.',
                                            'success'
                                        );
                                        LoadData();
                                    }
                                }
                            });
                        }
                        else if (result.dismiss === swal.DismissReason.cancel) {
                            Swal(
                              'Cancelled',
                              'Your imaginary file is safe :)',
                              'error'
                            );
                        }
                    })
                }
            });
        }

        function CheckNama() {
            var ini = $('#getModal').find('#name').val();
            $.ajax({
                url: '@Url.Action("CheckNama","Ajax")',
                type: 'get',
                dataType: 'json',
                data: { nama: ini },
                success: function (x) {
                    if (x.data == true) {
                        swal({
                            type: x.alertType,
                            title: x.alertStrong,
                            html: x.alertMessage
                        });
                    }
                }
            });
            return false;
        }

        $("#btn-add").click(function () {
            $.ajax({
                url: '@Url.Action("Insert")',
                type: 'get',
                dataType: 'html',
                success: function (x) {
                    $("#getModal").modal('show');
                    $("#getModal").find(".modal-title").html("Add Souvenir");
                    $("#getModal").find(".modal-body").html(x);
                }
            });
        });

        $("#getModal").on("submit", "#form-msouvenir", function () {
            vUrl = $(this).attr('action');
            vData = $(this).serialize();
            $.ajax({
                url: vUrl,
                type: 'post',
                dataType: 'json',
                data: vData,
                success: function (x) {
                    if (x.success == true) {
                        LoadData();
                        $("#getModal").modal('hide');
                        var response = '<div class="alert alert-' + x.alertType + ' alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><strong>' + x.alertMessage + '</strong> ' + x.alertStrong + '.</div>';
                        $('#AlertResponse').hide().html(response).fadeIn(1500);
                        $('.alert').delay(5000).fadeOut('normal', function () {
                            $(this).remove();
                        });
                    }
                    else {
                        swal({
                            type: x.alertType,
                            title: x.alertStrong,
                            html: x.alertMessage
                        })
                    }
                }
            });
            return false;
        });
    </script>
}

MiniProject.Web/Views/MSouvenir/Masking.cshtml
@model MiniProject.ViewModel.MSouvenirVM

@{
    ViewBag.Title = "Masking";
}

<h2>Masking</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MSouvenirVM</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control" id="code" name="code"  data-inputmask='"mask": "(999) 999-9999"' data-mask/>

                @Html.ValidationMessageFor(model => model.code, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MiniProject.Web/Views/MSouvenir/_Detail.cshtml
@model MiniProject.ViewModel.MSouvenirVM

<div class="form-horizontal">
    <div class="row">
        <div class="col-lg-6">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.code, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control", @readonly = "" } })
                    @Html.ValidationMessageFor(model => model.code, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", @readonly = "" } })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="form-group">
                @Html.LabelFor(model => model.str_unit, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownListFor(model => model.m_unit_id, (IEnumerable<SelectListItem>)ViewBag.listUnit, "-- Select Unit --", new { @class = "form-control", @disabled = "" })
                    @Html.ValidationMessageFor(model => model.m_unit_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control", @readonly = "" } })
                    @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <div class="col-md-offset-2 col-md-10">
            <button class="btn btn-warning" data-dismiss="modal" aria-label="Close">Close</button>
        </div>
    </div>
</div>
@Scripts.Render("~/bundles/jqueryval")

MiniProject.Web/Views/MSouvenir/_Insert.cshtml
@model MiniProject.ViewModel.MSouvenirVM

@using (Html.BeginForm("Insert", "Msouvenir", FormMethod.Post, new { @id = "form-msouvenir" }))
{
@Html.AntiForgeryToken()

<div class="form-horizontal">
    <div class="row">
        <div class="col-lg-6">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.code, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control", @readonly="", @Value= ViewBag.AutoCode } })
                    @Html.ValidationMessageFor(model => model.code, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", @onfocusout= "CheckNama()" } })
                    @*<input type="type" name="name" id="name" class="form-control" value="" onfocusout=""/>*@
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="form-group">
                @Html.LabelFor(model => model.str_unit, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownListFor(model => model.m_unit_id, (IEnumerable<SelectListItem>)ViewBag.listUnit, "-- Select Unit --", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.m_unit_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
    
    <div class="modal-footer">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
            <button class="btn btn-warning" data-dismiss="modal" aria-label="Close">Close</button>
        </div>
    </div>
</div>
}
@Scripts.Render("~/bundles/jqueryval")

MiniProject.Web/Views/MSouvenir/_List.cshtml
@model IEnumerable<MiniProject.ViewModel.MSouvenirVM>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(m => item.code)
        </td>
        <td>
            @Html.DisplayFor(m => item.name)
        </td>
        <td>
            @Html.DisplayFor(m => item.str_unit)
        </td>
        <td>
            @Html.DisplayFor(m => item.created_date)
        </td>
        <td>
            @Html.DisplayFor(m => item.str_created_by)
        </td>
        <td>
            
            <a href="#" onclick="clickbyID('Detail',@item.id)">
                <i class="fa fa-search"> </i>
            </a>
            &nbsp;
            <a href="#" onclick="clickbyID('Update',@item.id)">
                <i class="fa fa-edit"> </i>
            </a>
            &nbsp;
            <a href="#" onclick="Delete(@item.id)">
                <i class="fa fa-trash"> </i>
            </a>
        </td>
    </tr>
                }

MiniProject.Web/Views/MSouvenir/_Update.cshtml
@model MiniProject.ViewModel.MSouvenirVM

@using (Html.BeginForm("Update","MSouvenir", FormMethod.Post, new { @id="form-msouvenir"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="row">
            <div class="col-lg-6">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.code, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control", @readonly = "" } })
                        @Html.ValidationMessageFor(model => model.code, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.str_unit, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DropDownListFor(model => model.m_unit_id, (IEnumerable<SelectListItem>)ViewBag.listUnit, "-- Select Unit --", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.m_unit_id, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="modal-footer">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-primary" />
                <button class="btn btn-warning" data-dismiss="modal" aria-label="Close">Close</button>
            </div>
        </div>
    </div>
}
@Scripts.Render("~/bundles/jqueryval")