MiniProject.Web/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MiniProject.Model;
using MiniProject.VM;
using MiniProject.Repo;

namespace MiniProject.Web.Controllers
{
    public class AjaxController : Controller
    {
        // GET: Ajax
        public ActionResult GetById(int id)
        {
            var data = new
            {
                obj = MCompanyRepo.getbyid(id)
            };
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetById2(int id)
        {
            var data = new
            {
                obj = MEmployeeRepo.getbyid(id)
            };
            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

MiniProject.Web/Controllers/MUserController.cs
using MiniProject.Repo;
using MiniProject.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiniProject.Web.Controllers
{
    [Authorize]
    public class MUserController : Controller
    {
        // GET: MUser
        public ActionResult Index()
        {
            ViewBag.Title = "List User";
            ViewBag.ListRole = new SelectList(MRoleRepo.get(), "name", "name");
            ViewBag.ListEmployee = new SelectList(MEmployeeRepo.get(), "FullName", "FullName");
            ViewBag.ListCompany = new SelectList(MCompanyRepo.get(), "name", "name");
            return View(MUserRepo.get());
        }
        public ActionResult List()
        {
            return PartialView("_List", MUserRepo.get());
        }
        public ActionResult Details(int id)
        {
            var data = MUserRepo.getById(id);
            ViewBag.Title = "View User - " + data.firtsName + " " + data.lastName + "(" + data.username + ")";
            ViewBag.ListRole = new SelectList(MRoleRepo.get(), "id", "name");
            ViewBag.ListEmployee = new SelectList(MEmployeeRepo.get(), "id", "fullName");
            return PartialView("_Details", data);
        }
        public ActionResult Add()
        {
            ViewBag.Title = "Add User";
            ViewBag.ListRole = new SelectList(MRoleRepo.get(), "id", "name");
            ViewBag.ListEmployee = new SelectList(MEmployeeRepo.getDataNonUser(), "id", "FullName");
            return PartialView("_Add");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(MUserVM model)
        {
            if (ModelState.IsValid && MUserRepo.insert(model))
            {
                var result = new
                {
                    success = true,
                    message = "Data Saved! New User has been add with username " + model.username,
                    vclass = "alert alert-info"
                };
                return Json(result, JsonRequestBehavior.AllowGet);
            }

            ViewBag.Title = "Add User";
            ViewBag.ListRole = new SelectList(MRoleRepo.get(), "id", "name");
            ViewBag.ListEmployee = new SelectList(MEmployeeRepo.getDataNonUser(), "id", "FullName");
            return PartialView("_Add", model);
        }

        public ActionResult Edit(int id)
        {
            var data = MUserRepo.getById(id);
            ViewBag.Title = "Edit User - " + data.firtsName + " " + data.lastName + "(" + data.username + ")";
            ViewBag.ListRole = new SelectList(MRoleRepo.get(), "id", "name");
            ViewBag.ListEmployee = new SelectList(MEmployeeRepo.getDataNonUser(), "id", "FullName");
            return PartialView("_Edit", data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MUserVM model)
        {
            var data = MUserRepo.getById(model.id);
            if (ModelState.IsValid && MUserRepo.update(model))
            {
                var result = new
                {
                    success = true,
                    message = "Data Updated! Data User has been updated !",
                    vclass = "alert alert-info"
                };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            ViewBag.Title = "Edit User - " + data.firtsName + " " + data.lastName + "(" + data.username + ")";
            ViewBag.ListRole = new SelectList(MRoleRepo.get(), "id", "name");
            ViewBag.ListEmployee = new SelectList(MEmployeeRepo.getDataNonUser(), "id", "FullName");
            return PartialView("_Edit", model);
        }

        public ActionResult Delete(int id)
        {
            ViewBag.Title = "Delete Data?";
            var data = MUserRepo.getById(id);
            return PartialView("_Delete", data);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(MUserVM model)
        {
            if (MUserRepo.delete(model.id))
            {
                var result = new
                {
                    success = true,
                    message = "Data Deleted! Data User with Username" + model.username + " has been deleted!",
                    vclass = "alert alert-info"
                };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            return PartialView("_Delete", model);
        }

        public ActionResult Search(string user)
        {
            var data = MUserRepo.search(user);
            return PartialView("_List", data);
        }
    }
}

MiniProject.Web/Views/MUser/Index.cshtml
@model IEnumerable<MiniProject.ViewModel.MUserVM>

<div class="box box-solid box-primary">
    <div class="box-header">
        <h3 class="box-title">@ViewBag.Title</h3>
    </div>
    <div class="box-body">
        <ol class="breadcrumb">
            <li><a href="@Url.Action("index","home")">Home</a></li>
            <li><a href="@Url.Action("index","muser")">Master</a></li>
            <li class="active">@ViewBag.Title</li>
        </ol>
        <table id="tb-input" class="table no-border">
            <tr id="tr-warning">
                <td colspan="6"><div id="alert"></div></td>
                <td><button type="button" class="btn btn-primary btn-md" id="btn-add" style="width:80px">Add</button></td>
            </tr>
            <tr id="tr-input">
                <td>@Html.DropDownList("mEmployeeId", (IEnumerable<SelectListItem>)ViewBag.ListEmployee, "- Select Employee Name -", new { @class = "form-control col-md-2 column-filter select2", @minimal = "minimal", @data = "1", @id = "col1-filter" })</td>
                <td>@Html.DropDownList("mRoleId", (IEnumerable<SelectListItem>)ViewBag.ListRole, "- Select Role Name -", new { @class = "form-control column-filter col-md-2 select2", @minimal = "minimal", @data = "2", @id = "col2-filter" })</td>
                <td>@Html.DropDownList("mCompanyId", (IEnumerable<SelectListItem>)ViewBag.ListCompany, "- Select Company Name -", new { @class = "form-control column-filter col-md-2 select2", @minimal = "minimal", @data = "3", @id = "col3-filter" }) </td>
                <td><input class="column-filter form-control" data="4" id="col4-filter" type="text" placeholder="username" /> </td>
                <td>
                    <div class="input-group date">
                        <input class="column-filter form-control" data="5" id="col5-filter" type="text" name="createdDate" placeholder="Create Date" data-provide="datepicker" />
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                    </div>
                </td>
                <td><input class="column-filter form-control" data="6" id="col6-filter" type="text" placeholder="Created By" /> </td>
                <td><button type="button" class="btn btn-warning btn-md column-filter" id="btn-search" style="width:80px">Search</button></td>
            </tr>
        </table>
        <table class="table table-bordered table-striped" id="example1">
            <thead>
                <tr>
                    <th>
                        No
                    </th>
                    <th>
                        Employee
                    </th>
                    <th>
                        Role
                    </th>
                    <th>
                        Company
                    </th>
                    <th>
                        Username
                    </th>
                    <th>
                        Created Date
                    </th>
                    <th>
                        Created By
                    </th>
                    <th width="100">
                        Action
                    </th>
                </tr>
            </thead>
            <tbody id="list-data">
                @Html.Partial("_List", Model)
            </tbody>
        </table>
    </div>
</div>
<div class="modal fade" id="modal-input">
    <div class="modal-dialog" role="dialog">
        <div class="modal-body">

        </div>
    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            $('#example1').DataTable({
                'sDom': 'tip',
                'ordering': false
            });
            $("#btn-search").click(function () {
                $("#tb-input .form-control").each(function (i) {
                    filterColumn($(this).attr('data'))
                })
            });
        });
        function filterColumn(i) {
            $('#example1').DataTable().column(i).search(
                $('#col' + i + '-filter').val()
                ).draw();
        }
        function loadData() {
            $.ajax({
                url: '@Url.Action("List")',
                dataType: 'html',
                type: 'get',
                success: function (x) {
                    $("#list-data").html(x);
                }
            });
        }
        $("#btn-add").click(function () {
            $.ajax({
                url: '@Url.Action("Add")',
                dataType: 'html',
                type: 'get',
                success: function (x) {
                    $("#modal-input").find(".modal-dialog").removeClass("modal-sm");
                    $("#modal-input").find(".modal-dialog").addClass("modal-lg");
                    $("#modal-input").find(".modal-body").html(x);
                    $("#modal-input").modal('show');
                }
            });
        });

        $("#list-data").on("click", "#btn-detail", function () {
            $.ajax({
                url: '@Url.Action("Details")',
                dataType: 'html',
                type: 'get',
                data: { id: $(this).val() },
                success: function (x) {
                    $("#modal-input").find(".modal-dialog").removeClass("modal-sm");
                    $("#modal-input").find(".modal-dialog").addClass("modal-lg");
                    $("#modal-input").find(".modal-body").html(x);
                    $("#modal-input").modal('show');
                }
            });
        });

        $("#list-data").on("click", "#btn-edit", function () {
            $.ajax({
                url: '@Url.Action("Edit")',
                dataType: 'html',
                type: 'get',
                data: { id: $(this).val() },
                success: function (x) {
                    $("#modal-input").find(".modal-dialog").removeClass("modal-sm");
                    $("#modal-input").find(".modal-dialog").addClass("modal-lg");
                    $("#modal-input").find(".modal-body").html(x);
                    $("#modal-input").modal('show');
                }
            });
        });

        $("#list-data").on("click", "#btn-hapus", function () {
            $.ajax({
                url: '@Url.Action("Delete")',
                dataType: 'html',
                type: 'get',
                data: { id: $(this).val() },
                success: function (x) {
                    $("#modal-input").find(".modal-dialog").removeClass("modal-lg");
                    $("#modal-input").find(".modal-dialog").addClass("modal-sm");
                    $("#modal-input").find(".modal-body").html(x);
                    $("#modal-input").modal('show');
                }
            });
        });

        $("#modal-input").on("click", "#btn-cancel", function () {
            $("#modal-input").modal('hide');
        });

        $("#modal-input").on("submit", "#form-input", function () {
            $.ajax({
                url: $(this).attr('action'),
                data: $(this).serialize(),
                dataType: 'JSON',
                type: 'POST',
                success: function (data) {
                    if (data.success == true) {
                        $("#modal-input").modal('hide');
                        $("#alert").addClass(data.vclass);
                        $("#alert").fadeOut(5000).html(data.message);
                        loadData();
                    }
                    else {
                        $("#modal-input").find(".modal-body").html(data);

                        //$("#modal-input").modal('show');
                    }
                }
            });
            return false;
        });
        function cekData() {
            var ini = $('#modal-input').find('#username').val();
            $.ajax({
                url: '@Url.Action("CheckNama","Ajax")',
                type: 'get',
                dataType: 'json',
                data: {
                    nama: ini
                },
                success: function (x) {
                    if (x.data == true) {
                        swal({
                            type: x.alertType,
                            title: x.alertStrong,
                            html: x.alertMessage,
                            footer: ''
                        });
                    }
                }
            });
            return false;
        }
        $("#tb-input").find("#tr-input").find("#col5-filter").datepicker({
            autoclose: true,
            format: 'dd/mm/yyyy'
        });
        $(".select2").select2();
    </script>
}

MiniProject.Web/Views/MUser/_Add.cshtml
@model MiniProject.ViewModel.MUserVM

<div class="box box-solid box-primary">
    <div class="box-header">
        <h3 class="box-title">@ViewBag.Title</h3>
    </div>
    <div class="box-body with-border">
        @using (Html.BeginForm("Add", "MUser", FormMethod.Post, new { @id = "form-input" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <input type="hidden" name="createdBy" value="2" />
            <div class="form-horizontal">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label">*Role Name</label>
                        </div>
                        <div class="col-md-6">
                            @Html.DropDownListFor(model => model.mRoleId, (IEnumerable<SelectListItem>)ViewBag.ListRole, "- Select Role Name -", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.mRoleId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label">*Employee Name</label>
                        </div>
                        <div class="col-md-6">
                            @Html.DropDownListFor(model => model.mEmployeeId, (IEnumerable<SelectListItem>)ViewBag.ListEmployee, "- Select Employee Name -", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.mEmployeeId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label">*Username</label>
                        </div>
                        <div class="col-md-6">
                            @Html.EditorFor(Model => Model.username, new { HtmlAttributes = new { @class = "form-control", @placeholder = "Type Username" ,@onfocusout="cekData()"} })
                            @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label">*Password</label>
                        </div>
                        <div class="col-md-6">
                            @Html.EditorFor(Model => Model.password, new { HtmlAttributes = new { @class = "form-control", @placeholder = "Type Password" } })
                            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label">*Re-type Password</label>
                        </div>
                        <div class="col-md-6">
                            @Html.EditorFor(Model => Model.rePassword, new { HtmlAttributes = new { @class = "form-control", @placeholder = "Re-Type Password" } })
                            @Html.ValidationMessageFor(model => model.rePassword, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary btn-sm">Save</button>
                    <button type="button" class="btn btn-warning btn-sm" id="btn-cancel">Cancel</button>
                </div>
            </div>
        }
    </div>
</div>
@Scripts.Render("~/bundles/jqueryval")

MiniProject.Web/Views/MUser/_Delete.cshtml
@model MiniProject.ViewModel.MUserVM

<div class="box box-solid box-default">
    <div class="box-header">
        <h3 class="box-title" style="text-align:center">@ViewBag.Title</h3>
        <button class="btn btn-danger btn-xs box-tools" id="btn-cancel" data-dissmiss="modal" type="button"><i class="fa fa-times-rectangle"></i></button>
    </div>
    <div class="box-body with-border">
        @using (Html.BeginForm("Delete", "MUser", FormMethod.Post, new { @id = "form-input" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(Model => Model.id)
            <div class="form-horizontal">
                <div class="modal-footer" style="text-align:center">
                    <button type="submit" class="btn btn-primary btn-sm">Delete</button>
                    <button type="button" class="btn btn-warning btn-sm" id="btn-cancel">Cancel</button>
                </div>
            </div>
        }
    </div>
</div>
@Scripts.Render("~/bundles/jqueryval")

MiniProject.Web/Views/MUser/_Details.cshtml
@model MiniProject.ViewModel.MUserVM

<div class="box box-solid box-primary">
    <div class="box-header">
        <h3 class="box-title">@ViewBag.Title</h3>
    </div>
    <div class="box-body with-border">
        @using (Html.BeginForm("Add", "MUser", FormMethod.Post, new { @id = "form-input" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(Model => Model.id)
            <input type="hidden" name="createdBy" value="2" />
            <div class="form-horizontal">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label">*Role Name</label>
                        </div>
                        <div class="col-md-6">
                            @Html.TextBoxFor(model => model.nameRole, new { @class = "form-control" ,@readonly=""})
                            @Html.ValidationMessageFor(model => model.mRoleId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label">*Employee Name</label>
                        </div>
                        <div class="col-md-6">
                            @Html.TextBoxFor(model => model.firtsName,  new { @class = "form-control" ,@readonly=""})
                            @Html.ValidationMessageFor(model => model.mEmployeeId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label">*Username</label>
                        </div>
                        <div class="col-md-6">
                            <input type="text" class="form-control" name="username" placeholder="Type Username" value="@Model.username" readonly/>
                            @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label">*Password</label>
                        </div>
                        <div class="col-md-6">
                            <input type="password" name="password" class="form-control" placeholder="Type Password" value="@Model.password" readonly/>
                            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label">*Re-type Password</label>
                        </div>
                        <div class="col-md-6">
                            <input type="password" name="Repassword" class="form-control" placeholder="Re-Type Password" value="@Model.password" readonly/>
                            @Html.ValidationMessageFor(model => model.rePassword, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-warning btn-sm" id="btn-cancel">Close</button>
                </div>
            </div>
        }
    </div>
</div>
@Scripts.Render("~/bundles/jqueryval")

MiniProject.Web/Views/MUser/_Edit.cshtml
@model MiniProject.ViewModel.MUserVM

<div class="box box-solid box-primary">
    <div class="box-header">
        <h3 class="box-title">@ViewBag.Title</h3>
    </div>
    <div class="box-body with-border">
        @using (Html.BeginForm("Edit", "MUser", FormMethod.Post, new { @id = "form-input" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(Model => Model.id)
            <input type="hidden" name="createdBy" value="2" />
            <div class="form-horizontal">
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label">*Role Name</label>
                        </div>
                        <div class="col-md-6">
                            @Html.DropDownListFor(model => model.mRoleId, (IEnumerable<SelectListItem>)ViewBag.ListRole, "- Select Role Name -", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.mRoleId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label">*Employee Name</label>
                        </div>
                        <div class="col-md-6">
                            @Html.HiddenFor(model => model.mEmployeeId)
                            @Html.TextBoxFor(model => model.fullName, new { @class="form-control", @readonly=""})
                            @Html.ValidationMessageFor(model => model.mEmployeeId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label">*Username</label>
                        </div>
                        <div class="col-md-6">
                            @Html.EditorFor(model => model.username, new { HtmlAttributes =new {@class="form-control", @placeholder="Type Username", @onfocusout="cekData()"}})
                            @Html.ValidationMessageFor(model => model.username, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label">*Password</label>
                        </div>
                        <div class="col-md-6">
                            @Html.EditorFor(model => model.password, new { HtmlAttributes = new { @class = "form-control", @placeholder = "Type password" } })
                            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            <label class="control-label">*Re-type Password</label>
                        </div>
                        <div class="col-md-6">
                            @Html.EditorFor(model => model.rePassword, new { HtmlAttributes = new { @class = "form-control", @placeholder = "Re-Type Password" } })
                            @Html.ValidationMessageFor(model => model.rePassword, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary btn-sm">Save</button>
                    <button type="button" class="btn btn-warning btn-sm" id="btn-cancel">Cancel</button>
                </div>
            </div>
        }
    </div>
</div>
@Scripts.Render("~/bundles/jqueryval")

MiniProject.Web/Views/MUser/_List.cshtml
@model IEnumerable<MiniProject.ViewModel.MUserVM>
@{ int i = 1;}
@foreach (var item in Model)
{
    if (item.isActive == true)
    {
        <tr>
            <td>
                @i
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.firtsName) @Html.DisplayFor(modelItem => item.lastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nameRole)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.company)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.createdDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.createdBy)
            </td>

            <td style="width:80">
                <button type="button" id="btn-detail" value="@item.id" class="no-border"><i class="fa fa-search"></i></button>
                <button type="button" id="btn-edit" value="@item.id" class="no-border"><i class="fa fa-pencil"></i></button>
                <button type="button" id="btn-hapus" value="@item.id" class="no-border"><i class="fa fa-trash"></i></button>
            </td>
        </tr>
        i++;
    }
}