MiniProject.Web/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MiniProject.Model;
using MiniProject.VM;
using MiniProject.Repo;

namespace MiniProject.Web.Controllers
{
    public class AjaxController : Controller
    {
        // GET: Ajax
        public ActionResult GetById(int id)
        {
            var data = new
            {
                obj = MCompanyRepo.getbyid(id)
            };
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetById2(int id)
        {
            var data = new
            {
                obj = MEmployeeRepo.getbyid(id)
            };
            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

MiniProject.Web/Controllers/MEmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MiniProject.Model;
using MiniProject.VM;
using MiniProject.Repo;
namespace MiniProject.Web.Controllers
{
   
    public class MEmployeeController : Controller
    {
        // GET: m_employee
        public ActionResult Index()
        {
            ViewBag.Title = "List Employee";
            
            ViewBag.ListCompanyName = new SelectList(MEmployeeRepo.get(), "NmCompany", "NmCompany");

            List<MEmployeeVM> item = MEmployeeRepo.get();
            return View(item);
        }

        public ActionResult List()
        {
            ViewBag.Title = "List Employee";
            List<MEmployeeVM> item = MEmployeeRepo.get();
            return PartialView("_List",item);
        }

        public ActionResult Add()
        {
            MEmployeeVM model = new MEmployeeVM();
            ViewBag.ListCompany = new SelectList(MCompanyRepo.get(), "id", "name");
            ViewBag.Title = "Add";
            return PartialView("_Add",model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(MEmployeeVM model)
        {
            ViewBag.ListCompany = new SelectList(MCompanyRepo.get(), "id", "name");
            if (ModelState.IsValid)
            {
                if(MEmployeeRepo.HitungEmplo(model) == true)
                {
                    var result = new
                    {
                        success = true,
                        alertType = "warning",
                        alertStrong = "Error!",
                        alertMessage = "Employee number already used"
                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                else if (MEmployeeRepo.HitungEmplo(model) == false)
                {
                    MEmployeeRepo.insert(model);
                    var result = new
                    {
                        success = false,
                        alertType = "success",
                        alertStrong = "Data Saved !",
                        alertMessage = "New Employee has been add with employee ID number" + model.employee_number

                    };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }
            return PartialView("_Add", model);
        }

         public ActionResult Delete(int id)
        {
           MEmployeeVM model = MEmployeeRepo.getbyid(id);
            MEmployeeRepo.Delete(id);
            var result = new
            {
                success = true,
                alertType = "info",
                alertStrong = "Data Deleted !",
                alertMessage = "Data Deleted! Data Company With Employee ID Number" + model.employee_number + "Has been deleted"

            };
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        
        

        public ActionResult Detail(int id)
        {
            MEmployeeVM model = MEmployeeRepo.GetDetail(id);
            ViewBag.Title = "View Company-" + model.first_name + model.last_name+ "(" + model.employee_number + ")";


            return PartialView(model);
        }

        public ActionResult Edit(int id)
        {
            ViewBag.ListCompany = new SelectList(MCompanyRepo.get(), "id", "name");
            MEmployeeVM model = MEmployeeRepo.getbyid(id);
            ViewBag.Title = "Edit Company-" + model.first_name+model.last_name + "(" + model.employee_number + ")";
            return PartialView(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MEmployeeVM model)
        {
            ViewBag.ListCompany = new SelectList(MEmployeeRepo.get(), "id", "name");
            if (MEmployeeRepo.HitungEmplo(model) == true)
            {
                var result = new
                {
                    success = true,
                    alertType = "warning",
                    alertStrong = "Error!",
                    alertMessage = "Employee number already used"
                };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else if (MEmployeeRepo.HitungEmplo(model) == false)
            {
                MEmployeeRepo.update(model);
                var result = new
                {
                    success = false,
                    alertType = "success",
                    alertStrong = "Data Updated !",
                    alertMessage = "Data Updated! Data employee has been Updated"
                    
                };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            return PartialView(model);
        }

        public JsonResult CheckNama(string nama)
        {
            var result = new
            {
                success = true,
                data = MEmployeeRepo.CheckNama(nama),
                alertType = "error",
                alertStrong = "Error !",
                alertMessage = "Your Data with name </strong>(" + nama + ")</strong>Has been created"
            };
            return Json(result, JsonRequestBehavior.AllowGet);
        }


    }
}

MiniProject.Web/Views/MEmployee/Detail.cshtml
@model MiniProject.VM.MEmployeeVM


<div class="box-body">

    @Html.ValidationSummary()

    <div class="form-horizontal">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.employee_number, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.employee_number, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                    @Html.ValidationMessageFor(model => model.employee_number, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.first_name, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                    @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                    @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.m_company_id, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.m_company_id, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                    @Html.ValidationMessageFor(model => model.m_company_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <div class="col-md-12">
            <a href="@Url.Action("Index","MEmployee")"><button type="button" class="btn btn-warning pull-right">Close</button></a>
        </div>
    </div>
</div>



    

MiniProject.Web/Views/MEmployee/Edit.cshtml
@model MiniProject.VM.MEmployeeVM

@*<div class="box box-solid no-border box-primary">
    <div class="box-header">
        <h3 class="box-title">@ViewBag.Title</h3>
    </div>
    <div class="box-body no-border">*@

@using (Html.BeginForm("Edit", "MEmployee", FormMethod.Post, new { @id = "form-employee" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(m => m.id)

    <div class="form-horizontal">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.employee_number, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    <input type="text" id="employee_number" value="@Model.employee_number" name="employee_number" class="form-control" data-inputmask='"mask": "99.99.99.99"' data-mask onfocusout = "check()">
                    @Html.ValidationMessageFor(model => model.employee_number, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.first_name, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.m_company_id, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.DropDownListFor(model => model.m_company_id, (IEnumerable<SelectListItem>)ViewBag.ListCompany, "= Select Company Name =", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.m_company_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <div class="col-md-12">
            <input type="submit" value="Save" class="btn btn-default" id="btn-update" />
            <a href="@Url.Action("Index","m_company")"><button type="button" class="btn btn-warning">Cancel</button></a>
        </div>
    </div>

}

@*</div>
    </div>*@

<script>

    $(function () {
        $('[data-mask]').inputmask()
    })
</script>

MiniProject.Web/Views/MEmployee/Index.cshtml
@model IEnumerable<MiniProject.VM.MEmployeeVM>



<div class="box box-solid box-primary">
    <div class="box-header">
    </div>
    <div class="box-body">
        <ol class="breadcrumb">
            <li><a href="#"> Home</a></li>
            <li><a href="#"> Master</a></li>
            <li class="active">@ViewBag.Title</li>
        </ol>
            <div id="AlertResponse">

            </div>
        
        <table class="table table-bordered table-responsive table-striped table-condensed" id="example1">
            <thead id="tb-input">
                <tr class="no-border">
                    <td colspan="6" id="AlertResponse"></td>
                    <td>
                        <button type="button" class="btn btn-primary" id="btn-add" style="width:5em">Add </button>
                    </td>

                </tr>
                @Html.ValidationSummary()
                <tr id="tr-input">
                    <td></td>
                    <td>@Html.TextBox("employee_number", null, new { @class = "form-control column_filter", @placeholder = "Employee Id Number", @id = "col1_filter", @data = "1" })</td>
                    <td>@Html.TextBox("FullName", null, new { @class = "form-control column_filter", @placeholder = "Employee Name", @id = "col2_filter", @data = "2" })</td>
                    <td>@Html.DropDownList("NmCompany", (IEnumerable<SelectListItem>)ViewBag.ListCompanyName, "= Select Company Code =", new { @class = "column_filter form-control", @id = "col3_filter", @data = "3" })</td>
                    <td >
                        <div class="input-group date">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            <input type="text" class=" form-control column_filter datepicker" id="col4_filter" data="4" placeholder="Created">
                        </div>
                    </td>
                    <td>@Html.TextBox("created_by", null, new { @class = "form-control column_filter", @placeholder = "Created By", @id = "col5_filter", @data = "5" })</td>
                    <td>
                        <button type="button" class="btn btn-warning" id="btn-search" style="width:5em;">Search</button>
                    </td>
                </tr>
                <tr>
                    <th>No</th>
                    <th>
                        @Html.DisplayNameFor(model => model.employee_number)
                    </th>
                    <th>Employee Name</th>
                    <th>
                        @Html.DisplayNameFor(model => model.m_company_id)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.created_date)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.created_by)
                    </th>
                    <th> Action</th>
                </tr>
            </thead>
            <tbody id="list">
                @Html.Partial("_List", Model)
            </tbody>

        </table>
    </div>
</div>




<div class="modal fade" id="modal-input">
    <div class="modal-dialog modal-lg" role="dialog">
        <div class="box box-primary box-solid">
            <div class="box-header">
                <h3 class="box-title"></h3>
            </div>


            <div class="modal-body">

            </div>
        </div>
    </div>
</div>




@section Scripts{
    <script>

        function loaddata() {
            $.ajax({
                url: '@Url.Action("List","MEmployee")',
                type: "get",
                dataType: "html",
                success: function (result) {
                    $("#list").html(result);
                }
            });
        }

        $("#btn-add").on("click", function () {
            $.ajax({
                url: "@Url.Action("Add","MEmployee")",
                type: "get",
                datatype: "html",
                success: function (result) {
                    $("#modal-input").find(".box-title").html("Add Employee");
                    $("#modal-input").find(".modal-body").html(result);
                    $("#modal-input").modal('show');
                }

            })
        });


       $("#list").on("click", "#btn-detail", function () {
            var Id = $(this).val();

            $.ajax({
                url:"@Url.Action("GetById2","Ajax")",
                type:"get",
                datatype:"json",
                data: { id: Id },
                success: function (x) {
                    var vName = x.obj.FullName;
                    var vCode = x.obj.employee_number;
                    $.ajax({
                        url: "@Url.Action("Detail","MEmployee")",
                        type: "get",
                        datatype: "html",
                        data: { id: Id },
                        success: function (result) {
                            $("#modal-input").find(".box-title").html("View Employee-" + vName + "(" +vCode + ")");
                            $("#modal-input").find(".modal-body").html(result);
                            $("#modal-input").modal('show');
                        }
                    });
                }
            })

        });



        $("#list").on("click", "#btn-edit", function () {
            var Id = $(this).val();

            $.ajax({
                url:"@Url.Action("GetById2","Ajax")",
                type:"get",
                datatype:"json",
                data: { id: Id },
                success: function (x) {
                    var vName = x.obj.FullName;
                    var vCode = x.obj.employee_number;
                    $.ajax({
                        url: "@Url.Action("Edit","MEmployee")",
                        type: "get",
                        datatype: "html",
                        data: { id: Id },
                        success: function (result) {
                            $("#modal-input").find(".box-title").html("Edit Employee-" + vName + "(" +vCode + ")");
                            $("#modal-input").find(".modal-body").html(result);
                            $("#modal-input").modal('show');
                        }
                    });
                }
            })

        });

        $("#modal-input").on("submit", "#form-employee", function () {
            var vUrl = $(this).attr('action');
            var vData = $(this).serialize();
            $.ajax({
                url: vUrl,
                data: vData,
                dataType: 'JSON',
                method: 'POST',
                success: function (x) {
                    if (x.success == true) {
                        swal({
                            type: x.alertType,
                            title: x.alertStrong,
                            html: x.alertMessage,
                        });

                    }
                    else if (x.success == false) {
                        $("#modal-input").modal('hide');
                        loaddata();

                        var response = '<div class="alert alert-' + x.alertType + ' alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><strong>' + x.alertStrong + '</strong> ' + x.alertMessage + '.</div>';
                        $('#AlertResponse').hide().html(response).fadeIn(1500);
                        $('.alert').delay(5000).fadeOut('normal', function () {
                            $(this).remove();
                        });
                    }

                }
            });
            return false;
        });

        $(document).ready(function () {
            $('#example1').DataTable({
                'sDom': 'tip',
                ordering: false
            });
            $("#tb-input").find("#tr-input").find(".column_filter").on("keyup click", function () {
                filterColumn($(this).attr("data-column"));
            });

        });

        function filterColumn(i) {
            $("#example1").DataTable().column(i).search(
                $("#col" + i + "_filter").val()
                ).draw();
        }

        $("#btn-search").click(function () {
            $("#tb-input .form-control").each(function (i) {
                filterColumn($(this).attr('data'));
            })

        })


        $("#tb-input").find("#tr-input").find(".select2").select2();
        $("#tb-input").find("#tr-input").find(".datepicker").datepicker({

            format: "dd/mm/yyyy",
            autoclose: true
        });

        $("#list").on("click", "#btn-delete", function () {
            var Id = $(this).val()
            $.ajax({
                url: "@Url.Action("GetById2","Ajax")",
                type: "get",
                datatype: "json",
                data: { id: Id },
                success: function (x) {
                    Swal({
                        title: 'Delete ' + x.obj.Fullname + ' (' + x.obj.employee_number + ')?',
                        text: 'Are you sure?',
                        type: 'warning',
                        showCancelButton: true,
                        confirmButtonText: 'Yes, delete it!',
                        cancelButtonText: 'cancel!',
                        reverseButtons: true
                    }).then((result) => {
                        if (result.value) {
                            $.ajax({
                                url: '/MEmployee/Delete/' + Id,
                                type: 'get',
                                dataType: 'json',
                                success: function (x) {
                                    if (x.success == true) {
                                        swal(
                                            'Deleted!',
                                            'Employee has been deleted.',
                                            'success'
                                        );
                                    }

                                    loaddata();

                                }
                            });
                        }
                        else if (result.dismiss === swal.DismissReason.cancel) {
                            Swal(
                              'Cancelled',
                              'Your imaginary file is safe :)',
                              'warning'
                            );
                        }
                    })
                }
            });
        });

        function check() {
            var ini = $("#modal-input").find("#employee_number").val();
            $.ajax({
                url: "@Url.Action("CheckNama")",
                type: "get",
                datatype: "json",
                data: { nama: ini },
                success: function (x) {
                    if (x.data == true) {
                        swal({
                            type: x.alertType,
                            title: x.alertStrong,
                            html: x.alertMessage,
                        });

                    };

                }

            });
            return false;
        }

    </script>
}

MiniProject.Web/Views/MEmployee/_Add.cshtml
@model MiniProject.VM.MEmployeeVM

@*<div class="box box-solid no-border box-primary">
    <div class="box-header">
        <h3 class="box-title">Add Company</h3>
    </div>
    <div class="box-body no-border">*@

        @using (Html.BeginForm("Add","MEmployee",FormMethod.Post, new { @id="form-employee"}))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-horizontal">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.employee_number, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            
                           <input type="text" id="employee_number" name="employee_number" class="form-control" value="" onfocusout = "check()" data-inputmask='"mask": "99.99.99.99"' data-mask placeholder="Type Emp ID Number"  >
                            @Html.ValidationMessageFor(model => model.employee_number, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.first_name, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Type First Name" } })
                            @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Type Last Name" } })
                            @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.m_company_id, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.DropDownListFor(model => model.m_company_id, (IEnumerable<SelectListItem>)ViewBag.ListCompany, "= Select Company Name =", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.m_company_id, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-4" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Type Email" } })
                            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                        <a href="@Url.Action("Index","MEmployee")"><button type="button" class="btn btn-warning">Cancel</button></a>
                    </div>
                </div>
            </div>
        }

    @*</div>
</div>*@

@Scripts.Render("~/bundles/jqueryval")

<script>
    $(function () {
        $('[data-mask]').inputmask()
    })
    
</script>

MiniProject.Web/Views/MEmployee/_Delete.cshtml
@model MiniProject.VM.MEmployeeVM

@{
    ViewBag.Title = "Delete Employee";
}

@using (Html.BeginForm("Delete", "MEmployee", FormMethod.Post, new { @id = "form-employee" }))
{
    @Html.HiddenFor(m => m.id)
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(m=>m.employee_number)
    @Html.HiddenFor(m => m.first_name)
    @Html.HiddenFor(m => m.m_company_id)

    <div class="form-group" style="text-align:center">
        <button type="submit" class="btn btn-info">Delete</button>
        <a href="@Url.Action("Index","MEmployee")"><button type="button" class="btn btn-warning">Cancel</button></a>
    </div>



}

MiniProject.Web/Views/MEmployee/_List.cshtml
@model IEnumerable<MiniProject.VM.MEmployeeVM>
@{ int i = 1; }
@foreach (var item in Model)
{
    @Html.HiddenFor(modelItem => item.id)
    if (item.is_active == true)
    {
        <tr>
            <td>@i</td>
            <td>
                @Html.DisplayFor(modelItem => item.employee_number)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NmCompany)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.created_date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.created_by)
            </td>
            <td width="100">
                <button type="button" class="fa fa-search" id="btn-detail" value="@item.id"></button>
                <button type="button" class="fa fa-edit" id="btn-edit" value="@item.id"></button>
                <button type="button" class="fa fa-trash" id="btn-delete" value="@item.id"></button>
            </td>
        </tr>
        i++;
    }

}